In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
d1 = np.array([1,2,3,4,5])

In [4]:
d1

array([1, 2, 3, 4, 5])

In [5]:
np.ndim(d1)

1

In [6]:
d2 = np.array([[1,2,3],[10,20,30]])

In [7]:
np.ndim(d2)

2

In [17]:
import time

# python list

l1 = list(range(1,50000001))

start = time.time()

l2 = [i*2 for i in l1]

print('Time taken', time.time() - start )

Time taken 23.931669235229492


In [18]:
arr = np.array(range(1,50000001))

start = time.time()

arr2 = arr * 2

print('Time taken', time.time() - start )

Time taken 0.37813425064086914


In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
d1

array([1, 2, 3, 4, 5])

In [20]:
d1 + 10

array([11, 12, 13, 14, 15])

In [21]:
d1 * 2

array([ 2,  4,  6,  8, 10])

In [22]:
d1 ** 2

array([ 1,  4,  9, 16, 25])

In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
data1 = np.linspace(10,15,50)

In [9]:
data1

array([10.        , 10.10204082, 10.20408163, 10.30612245, 10.40816327,
       10.51020408, 10.6122449 , 10.71428571, 10.81632653, 10.91836735,
       11.02040816, 11.12244898, 11.2244898 , 11.32653061, 11.42857143,
       11.53061224, 11.63265306, 11.73469388, 11.83673469, 11.93877551,
       12.04081633, 12.14285714, 12.24489796, 12.34693878, 12.44897959,
       12.55102041, 12.65306122, 12.75510204, 12.85714286, 12.95918367,
       13.06122449, 13.16326531, 13.26530612, 13.36734694, 13.46938776,
       13.57142857, 13.67346939, 13.7755102 , 13.87755102, 13.97959184,
       14.08163265, 14.18367347, 14.28571429, 14.3877551 , 14.48979592,
       14.59183673, 14.69387755, 14.79591837, 14.89795918, 15.        ])

In [11]:
data1.size

50

In [14]:
a2 = np.array([[1,2,3], [10,20,30]])

In [15]:
a2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [18]:
a2[0]

array([1, 2, 3])

In [19]:
a2[0,1]

2

In [20]:
a2[1]

array([10, 20, 30])

In [21]:
a2[1,2]

30

In [22]:
sales = np.array([100,2494,5463,4874,4874])

In [23]:
np.sum(sales)

17805

In [24]:
np.average(sales)

3561.0

In [29]:
np.random.randint(1,25,5)

array([ 5,  2, 22,  3,  3])